exclude: ['README.md']
pygments: true
# safe: false

# Site settings
title: MIND LOG
subtitle: Celebrating Human Minds
description: Personal site for collaborative learning.
author: pmixer
email: dreaming underscore hz at hotmail dot com
timezone: Asia/Shanghai
url: "https://pay4trip.bid/"

# social
github_url:  https://github.com/pmixer
linkedin_url: https://www.linkedin.com/in/pmixer/

# Build settings
encoding: UTF-8
markdown: redcarpet
permalink: pretty

highlighter: rouge

redcarpet:
  input: Markdown
  # auto_ids: true
  syntax_highlighter: rouge
